### ISSUE TITLE
Contact Form Functioning

### ISSUE THREAD

**Issue by mqsmith** [mqsmith/slapBet#30]
## User Story
As a user, I want to be able to submit issues via a contact form so that when there is a problem it can be resolved. 

## Acceptance Criteria
- [x] Create a slapbetinfo@gmail.com email address
- [x] Grab the user input from the contact form and when they click submit it will automatically send that information our new gmail account.

**Comment by fwilbor** [comment]
set html to code to capture user input with and send email to slapbetinfo@gmail.com . Will add styling with either media queries or working with bootstrap forms
